// Bundles the frontend into .bundle.js scripts.
// Run via `task build-frontend`.

import { build } from 'esbuild'

const banner = '/* PrettyGCode bundle - generated by \'task build-frontend\', do not edit */'

const bundles = [
  { entryPoints: ['frontend/pg-main.ts'], outfile: 'octoprint_prettygcode/static/js/pg-main.bundle.js' },
  { entryPoints: ['frontend/src/gcode/parser-worker.ts'], outfile: 'octoprint_prettygcode/static/js/pg-gcode-parser-worker.bundle.js' }
]

await Promise.all(bundles.map((bundle) => build({
  ...bundle,
  bundle: true,
  banner: { js: banner },
  minifyWhitespace: true,
  minifyIdentifiers: true,
  // Must stay false: minifySyntax turns "\n" literals into raw newline bytes that OctoPrint's
  // plugin-bundle wrapper indents and corrupts, breaking our bundle.
  // If set to true, the nozzle and objects no longer appear on the bed plate.
  minifySyntax: false
})))
