[build-system]
requires = [
    "setuptools>=68",
]
build-backend = "setuptools.build_meta"

[project]
name = "OctoPrint-PrettyGCode"
version = "2.5.1"
description = "Pretty G-code Visualizer"
authors = [
    { name = "Jacopo Tediosi", email = "jacopotediosi@gmail.com" },
    { name = "Kragrathea", email = "redacted@example.com" },
]
requires-python = ">=3.7,<4"
dependencies = [
    "typing_extensions>=4.4",  # For typing_extensions.override
]
dynamic = [
    "license",
]

[project.entry-points."octoprint.plugin"]
prettygcode = "octoprint_prettygcode"

[project.urls]
Homepage = "https://github.com/jacopotediosi/OctoPrint-PrettyGCode"

[project.optional-dependencies]
develop = [
    "go-task-bin",
    "nodeenv",
]

[dependency-groups]
typechecking = [
    "OctoPrint",
]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[tool.setuptools]
include-package-data = true
license-files = [
    "LICENSE.txt",
    "THIRDPARTYLICENSES.md",
]

[tool.setuptools.packages.find]
include = [
    "octoprint_prettygcode",
    "octoprint_prettygcode.*",
]

[tool.ruff]
line-length = 120
fix = true

[tool.ruff.lint]
select = [
    "ALL",
]
ignore = [
    "CPY001", # missing-copyright-notice
    "D100", # undocumented-public-module
    "D101", # undocumented-public-class
    "D104", # undocumented-public-package
    "E501", # line-too-long
    "S101", # assert
]

[tool.codespell]
skip = "octoprint_prettygcode/static/js/*.bundle.js,package-lock.json"
